#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailingLabelApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DISPOSALDATA")]
	public partial class DataClassesAddressDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    #endregion
		
		public DataClassesAddressDataContext() : 
				base(global::MailingLabelApp.Properties.Settings.Default.DISPOSALDATAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAddressDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAddressDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAddressDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAddressDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerNumber;
		
		private int _SequenceNumber;
		
		private string _RouteLocation_FirstName;
		
		private string _RouteLocation_LastName;
		
		private string _RouteLocation_Address;
		
		private string _RouteLocation_City;
		
		private string _RouteLocation_State;
		
		private string _RouteLocation_ZipCode;
		
		private string _Billing_FirstName;
		
		private string _Billing_LastName;
		
		private string _Billing_Address;
		
		private string _Billing_City;
		
		private string _Billing_State;
		
		private string _Billing_ZipCode;
		
		private string _BusinessPhone;
		
		private string _HomePhone;
		
		private System.Nullable<int> _PickupDay;
		
		private System.Nullable<bool> _BillingSameAsRoute;
		
		private System.Nullable<double> _TaxRate;
		
		private System.Nullable<int> _BillingType;
		
		private string _SpecialInstructions;
		
		private System.Nullable<int> _Route;
		
		private int _LastMonthBilled;
		
		private int _MonthsToBill;
		
		private System.Nullable<double> _LastPaymentAmount;
		
		private System.Nullable<System.DateTime> _LastPaymentDate;
		
		private System.Nullable<double> _Balance;
		
		private string _AdditionalChargeDesc1;
		
		private string _AdditionalChargeDesc2;
		
		private string _Comments;
		
		private System.Nullable<double> _CurrentBalance;
		
		private System.Nullable<System.DateTime> _CurrentBalanceDate;
		
		private System.Nullable<double> _AgingBalanceCurrent;
		
		private System.Nullable<double> _AgingBalance3Month;
		
		private System.Nullable<double> _AgingBalance4Month;
		
		private System.Nullable<double> _AgingBalance5Month;
		
		private System.Nullable<int> _PreviousMonthBilled;
		
		private System.Nullable<bool> _GoInAfter;
		
		private System.Nullable<double> _GoInAfterAmount;
		
		private System.Nullable<bool> _SendToCollections;
		
		private System.Nullable<bool> _ContinueBilling;
		
		private string _CollectionNotes;
		
		private System.Nullable<bool> _YellowTab;
		
		private System.Nullable<int> _PreviousSequenceNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerNumberChanging(int value);
    partial void OnCustomerNumberChanged();
    partial void OnSequenceNumberChanging(int value);
    partial void OnSequenceNumberChanged();
    partial void OnRouteLocation_FirstNameChanging(string value);
    partial void OnRouteLocation_FirstNameChanged();
    partial void OnRouteLocation_LastNameChanging(string value);
    partial void OnRouteLocation_LastNameChanged();
    partial void OnRouteLocation_AddressChanging(string value);
    partial void OnRouteLocation_AddressChanged();
    partial void OnRouteLocation_CityChanging(string value);
    partial void OnRouteLocation_CityChanged();
    partial void OnRouteLocation_StateChanging(string value);
    partial void OnRouteLocation_StateChanged();
    partial void OnRouteLocation_ZipCodeChanging(string value);
    partial void OnRouteLocation_ZipCodeChanged();
    partial void OnBilling_FirstNameChanging(string value);
    partial void OnBilling_FirstNameChanged();
    partial void OnBilling_LastNameChanging(string value);
    partial void OnBilling_LastNameChanged();
    partial void OnBilling_AddressChanging(string value);
    partial void OnBilling_AddressChanged();
    partial void OnBilling_CityChanging(string value);
    partial void OnBilling_CityChanged();
    partial void OnBilling_StateChanging(string value);
    partial void OnBilling_StateChanged();
    partial void OnBilling_ZipCodeChanging(string value);
    partial void OnBilling_ZipCodeChanged();
    partial void OnBusinessPhoneChanging(string value);
    partial void OnBusinessPhoneChanged();
    partial void OnHomePhoneChanging(string value);
    partial void OnHomePhoneChanged();
    partial void OnPickupDayChanging(System.Nullable<int> value);
    partial void OnPickupDayChanged();
    partial void OnBillingSameAsRouteChanging(System.Nullable<bool> value);
    partial void OnBillingSameAsRouteChanged();
    partial void OnTaxRateChanging(System.Nullable<double> value);
    partial void OnTaxRateChanged();
    partial void OnBillingTypeChanging(System.Nullable<int> value);
    partial void OnBillingTypeChanged();
    partial void OnSpecialInstructionsChanging(string value);
    partial void OnSpecialInstructionsChanged();
    partial void OnRouteChanging(System.Nullable<int> value);
    partial void OnRouteChanged();
    partial void OnLastMonthBilledChanging(int value);
    partial void OnLastMonthBilledChanged();
    partial void OnMonthsToBillChanging(int value);
    partial void OnMonthsToBillChanged();
    partial void OnLastPaymentAmountChanging(System.Nullable<double> value);
    partial void OnLastPaymentAmountChanged();
    partial void OnLastPaymentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastPaymentDateChanged();
    partial void OnBalanceChanging(System.Nullable<double> value);
    partial void OnBalanceChanged();
    partial void OnAdditionalChargeDesc1Changing(string value);
    partial void OnAdditionalChargeDesc1Changed();
    partial void OnAdditionalChargeDesc2Changing(string value);
    partial void OnAdditionalChargeDesc2Changed();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnCurrentBalanceChanging(System.Nullable<double> value);
    partial void OnCurrentBalanceChanged();
    partial void OnCurrentBalanceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentBalanceDateChanged();
    partial void OnAgingBalanceCurrentChanging(System.Nullable<double> value);
    partial void OnAgingBalanceCurrentChanged();
    partial void OnAgingBalance3MonthChanging(System.Nullable<double> value);
    partial void OnAgingBalance3MonthChanged();
    partial void OnAgingBalance4MonthChanging(System.Nullable<double> value);
    partial void OnAgingBalance4MonthChanged();
    partial void OnAgingBalance5MonthChanging(System.Nullable<double> value);
    partial void OnAgingBalance5MonthChanged();
    partial void OnPreviousMonthBilledChanging(System.Nullable<int> value);
    partial void OnPreviousMonthBilledChanged();
    partial void OnGoInAfterChanging(System.Nullable<bool> value);
    partial void OnGoInAfterChanged();
    partial void OnGoInAfterAmountChanging(System.Nullable<double> value);
    partial void OnGoInAfterAmountChanged();
    partial void OnSendToCollectionsChanging(System.Nullable<bool> value);
    partial void OnSendToCollectionsChanged();
    partial void OnContinueBillingChanging(System.Nullable<bool> value);
    partial void OnContinueBillingChanged();
    partial void OnCollectionNotesChanging(string value);
    partial void OnCollectionNotesChanged();
    partial void OnYellowTabChanging(System.Nullable<bool> value);
    partial void OnYellowTabChanged();
    partial void OnPreviousSequenceNumberChanging(System.Nullable<int> value);
    partial void OnPreviousSequenceNumberChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CustomerNumber
		{
			get
			{
				return this._CustomerNumber;
			}
			set
			{
				if ((this._CustomerNumber != value))
				{
					this.OnCustomerNumberChanging(value);
					this.SendPropertyChanging();
					this._CustomerNumber = value;
					this.SendPropertyChanged("CustomerNumber");
					this.OnCustomerNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequenceNumber", DbType="Int NOT NULL")]
		public int SequenceNumber
		{
			get
			{
				return this._SequenceNumber;
			}
			set
			{
				if ((this._SequenceNumber != value))
				{
					this.OnSequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._SequenceNumber = value;
					this.SendPropertyChanged("SequenceNumber");
					this.OnSequenceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteLocation_FirstName", DbType="NVarChar(15)")]
		public string RouteLocation_FirstName
		{
			get
			{
				return this._RouteLocation_FirstName;
			}
			set
			{
				if ((this._RouteLocation_FirstName != value))
				{
					this.OnRouteLocation_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._RouteLocation_FirstName = value;
					this.SendPropertyChanged("RouteLocation_FirstName");
					this.OnRouteLocation_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteLocation_LastName", DbType="NVarChar(20)")]
		public string RouteLocation_LastName
		{
			get
			{
				return this._RouteLocation_LastName;
			}
			set
			{
				if ((this._RouteLocation_LastName != value))
				{
					this.OnRouteLocation_LastNameChanging(value);
					this.SendPropertyChanging();
					this._RouteLocation_LastName = value;
					this.SendPropertyChanged("RouteLocation_LastName");
					this.OnRouteLocation_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteLocation_Address", DbType="NVarChar(100)")]
		public string RouteLocation_Address
		{
			get
			{
				return this._RouteLocation_Address;
			}
			set
			{
				if ((this._RouteLocation_Address != value))
				{
					this.OnRouteLocation_AddressChanging(value);
					this.SendPropertyChanging();
					this._RouteLocation_Address = value;
					this.SendPropertyChanged("RouteLocation_Address");
					this.OnRouteLocation_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteLocation_City", DbType="NVarChar(30)")]
		public string RouteLocation_City
		{
			get
			{
				return this._RouteLocation_City;
			}
			set
			{
				if ((this._RouteLocation_City != value))
				{
					this.OnRouteLocation_CityChanging(value);
					this.SendPropertyChanging();
					this._RouteLocation_City = value;
					this.SendPropertyChanged("RouteLocation_City");
					this.OnRouteLocation_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteLocation_State", DbType="NVarChar(15)")]
		public string RouteLocation_State
		{
			get
			{
				return this._RouteLocation_State;
			}
			set
			{
				if ((this._RouteLocation_State != value))
				{
					this.OnRouteLocation_StateChanging(value);
					this.SendPropertyChanging();
					this._RouteLocation_State = value;
					this.SendPropertyChanged("RouteLocation_State");
					this.OnRouteLocation_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteLocation_ZipCode", DbType="NVarChar(15)")]
		public string RouteLocation_ZipCode
		{
			get
			{
				return this._RouteLocation_ZipCode;
			}
			set
			{
				if ((this._RouteLocation_ZipCode != value))
				{
					this.OnRouteLocation_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._RouteLocation_ZipCode = value;
					this.SendPropertyChanged("RouteLocation_ZipCode");
					this.OnRouteLocation_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billing_FirstName", DbType="NVarChar(15)")]
		public string Billing_FirstName
		{
			get
			{
				return this._Billing_FirstName;
			}
			set
			{
				if ((this._Billing_FirstName != value))
				{
					this.OnBilling_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._Billing_FirstName = value;
					this.SendPropertyChanged("Billing_FirstName");
					this.OnBilling_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billing_LastName", DbType="NVarChar(20)")]
		public string Billing_LastName
		{
			get
			{
				return this._Billing_LastName;
			}
			set
			{
				if ((this._Billing_LastName != value))
				{
					this.OnBilling_LastNameChanging(value);
					this.SendPropertyChanging();
					this._Billing_LastName = value;
					this.SendPropertyChanged("Billing_LastName");
					this.OnBilling_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billing_Address", DbType="NVarChar(100)")]
		public string Billing_Address
		{
			get
			{
				return this._Billing_Address;
			}
			set
			{
				if ((this._Billing_Address != value))
				{
					this.OnBilling_AddressChanging(value);
					this.SendPropertyChanging();
					this._Billing_Address = value;
					this.SendPropertyChanged("Billing_Address");
					this.OnBilling_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billing_City", DbType="NVarChar(30)")]
		public string Billing_City
		{
			get
			{
				return this._Billing_City;
			}
			set
			{
				if ((this._Billing_City != value))
				{
					this.OnBilling_CityChanging(value);
					this.SendPropertyChanging();
					this._Billing_City = value;
					this.SendPropertyChanged("Billing_City");
					this.OnBilling_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billing_State", DbType="NVarChar(15)")]
		public string Billing_State
		{
			get
			{
				return this._Billing_State;
			}
			set
			{
				if ((this._Billing_State != value))
				{
					this.OnBilling_StateChanging(value);
					this.SendPropertyChanging();
					this._Billing_State = value;
					this.SendPropertyChanged("Billing_State");
					this.OnBilling_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billing_ZipCode", DbType="NVarChar(15)")]
		public string Billing_ZipCode
		{
			get
			{
				return this._Billing_ZipCode;
			}
			set
			{
				if ((this._Billing_ZipCode != value))
				{
					this.OnBilling_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._Billing_ZipCode = value;
					this.SendPropertyChanged("Billing_ZipCode");
					this.OnBilling_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessPhone", DbType="NVarChar(20)")]
		public string BusinessPhone
		{
			get
			{
				return this._BusinessPhone;
			}
			set
			{
				if ((this._BusinessPhone != value))
				{
					this.OnBusinessPhoneChanging(value);
					this.SendPropertyChanging();
					this._BusinessPhone = value;
					this.SendPropertyChanged("BusinessPhone");
					this.OnBusinessPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePhone", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HomePhone
		{
			get
			{
				return this._HomePhone;
			}
			set
			{
				if ((this._HomePhone != value))
				{
					this.OnHomePhoneChanging(value);
					this.SendPropertyChanging();
					this._HomePhone = value;
					this.SendPropertyChanged("HomePhone");
					this.OnHomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PickupDay", DbType="Int")]
		public System.Nullable<int> PickupDay
		{
			get
			{
				return this._PickupDay;
			}
			set
			{
				if ((this._PickupDay != value))
				{
					this.OnPickupDayChanging(value);
					this.SendPropertyChanging();
					this._PickupDay = value;
					this.SendPropertyChanged("PickupDay");
					this.OnPickupDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingSameAsRoute", DbType="Bit")]
		public System.Nullable<bool> BillingSameAsRoute
		{
			get
			{
				return this._BillingSameAsRoute;
			}
			set
			{
				if ((this._BillingSameAsRoute != value))
				{
					this.OnBillingSameAsRouteChanging(value);
					this.SendPropertyChanging();
					this._BillingSameAsRoute = value;
					this.SendPropertyChanged("BillingSameAsRoute");
					this.OnBillingSameAsRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Float")]
		public System.Nullable<double> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this.OnTaxRateChanging(value);
					this.SendPropertyChanging();
					this._TaxRate = value;
					this.SendPropertyChanged("TaxRate");
					this.OnTaxRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingType", DbType="Int")]
		public System.Nullable<int> BillingType
		{
			get
			{
				return this._BillingType;
			}
			set
			{
				if ((this._BillingType != value))
				{
					this.OnBillingTypeChanging(value);
					this.SendPropertyChanging();
					this._BillingType = value;
					this.SendPropertyChanged("BillingType");
					this.OnBillingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialInstructions", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SpecialInstructions
		{
			get
			{
				return this._SpecialInstructions;
			}
			set
			{
				if ((this._SpecialInstructions != value))
				{
					this.OnSpecialInstructionsChanging(value);
					this.SendPropertyChanging();
					this._SpecialInstructions = value;
					this.SendPropertyChanged("SpecialInstructions");
					this.OnSpecialInstructionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="Int")]
		public System.Nullable<int> Route
		{
			get
			{
				return this._Route;
			}
			set
			{
				if ((this._Route != value))
				{
					this.OnRouteChanging(value);
					this.SendPropertyChanging();
					this._Route = value;
					this.SendPropertyChanged("Route");
					this.OnRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMonthBilled", DbType="Int NOT NULL")]
		public int LastMonthBilled
		{
			get
			{
				return this._LastMonthBilled;
			}
			set
			{
				if ((this._LastMonthBilled != value))
				{
					this.OnLastMonthBilledChanging(value);
					this.SendPropertyChanging();
					this._LastMonthBilled = value;
					this.SendPropertyChanged("LastMonthBilled");
					this.OnLastMonthBilledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthsToBill", DbType="Int NOT NULL")]
		public int MonthsToBill
		{
			get
			{
				return this._MonthsToBill;
			}
			set
			{
				if ((this._MonthsToBill != value))
				{
					this.OnMonthsToBillChanging(value);
					this.SendPropertyChanging();
					this._MonthsToBill = value;
					this.SendPropertyChanged("MonthsToBill");
					this.OnMonthsToBillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPaymentAmount", DbType="Float")]
		public System.Nullable<double> LastPaymentAmount
		{
			get
			{
				return this._LastPaymentAmount;
			}
			set
			{
				if ((this._LastPaymentAmount != value))
				{
					this.OnLastPaymentAmountChanging(value);
					this.SendPropertyChanging();
					this._LastPaymentAmount = value;
					this.SendPropertyChanged("LastPaymentAmount");
					this.OnLastPaymentAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPaymentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastPaymentDate
		{
			get
			{
				return this._LastPaymentDate;
			}
			set
			{
				if ((this._LastPaymentDate != value))
				{
					this.OnLastPaymentDateChanging(value);
					this.SendPropertyChanging();
					this._LastPaymentDate = value;
					this.SendPropertyChanged("LastPaymentDate");
					this.OnLastPaymentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Float")]
		public System.Nullable<double> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalChargeDesc1", DbType="NVarChar(100)")]
		public string AdditionalChargeDesc1
		{
			get
			{
				return this._AdditionalChargeDesc1;
			}
			set
			{
				if ((this._AdditionalChargeDesc1 != value))
				{
					this.OnAdditionalChargeDesc1Changing(value);
					this.SendPropertyChanging();
					this._AdditionalChargeDesc1 = value;
					this.SendPropertyChanged("AdditionalChargeDesc1");
					this.OnAdditionalChargeDesc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalChargeDesc2", DbType="NVarChar(100)")]
		public string AdditionalChargeDesc2
		{
			get
			{
				return this._AdditionalChargeDesc2;
			}
			set
			{
				if ((this._AdditionalChargeDesc2 != value))
				{
					this.OnAdditionalChargeDesc2Changing(value);
					this.SendPropertyChanging();
					this._AdditionalChargeDesc2 = value;
					this.SendPropertyChanged("AdditionalChargeDesc2");
					this.OnAdditionalChargeDesc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentBalance", DbType="Float")]
		public System.Nullable<double> CurrentBalance
		{
			get
			{
				return this._CurrentBalance;
			}
			set
			{
				if ((this._CurrentBalance != value))
				{
					this.OnCurrentBalanceChanging(value);
					this.SendPropertyChanging();
					this._CurrentBalance = value;
					this.SendPropertyChanged("CurrentBalance");
					this.OnCurrentBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentBalanceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentBalanceDate
		{
			get
			{
				return this._CurrentBalanceDate;
			}
			set
			{
				if ((this._CurrentBalanceDate != value))
				{
					this.OnCurrentBalanceDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentBalanceDate = value;
					this.SendPropertyChanged("CurrentBalanceDate");
					this.OnCurrentBalanceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgingBalanceCurrent", DbType="Float")]
		public System.Nullable<double> AgingBalanceCurrent
		{
			get
			{
				return this._AgingBalanceCurrent;
			}
			set
			{
				if ((this._AgingBalanceCurrent != value))
				{
					this.OnAgingBalanceCurrentChanging(value);
					this.SendPropertyChanging();
					this._AgingBalanceCurrent = value;
					this.SendPropertyChanged("AgingBalanceCurrent");
					this.OnAgingBalanceCurrentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgingBalance3Month", DbType="Float")]
		public System.Nullable<double> AgingBalance3Month
		{
			get
			{
				return this._AgingBalance3Month;
			}
			set
			{
				if ((this._AgingBalance3Month != value))
				{
					this.OnAgingBalance3MonthChanging(value);
					this.SendPropertyChanging();
					this._AgingBalance3Month = value;
					this.SendPropertyChanged("AgingBalance3Month");
					this.OnAgingBalance3MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgingBalance4Month", DbType="Float")]
		public System.Nullable<double> AgingBalance4Month
		{
			get
			{
				return this._AgingBalance4Month;
			}
			set
			{
				if ((this._AgingBalance4Month != value))
				{
					this.OnAgingBalance4MonthChanging(value);
					this.SendPropertyChanging();
					this._AgingBalance4Month = value;
					this.SendPropertyChanged("AgingBalance4Month");
					this.OnAgingBalance4MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgingBalance5Month", DbType="Float")]
		public System.Nullable<double> AgingBalance5Month
		{
			get
			{
				return this._AgingBalance5Month;
			}
			set
			{
				if ((this._AgingBalance5Month != value))
				{
					this.OnAgingBalance5MonthChanging(value);
					this.SendPropertyChanging();
					this._AgingBalance5Month = value;
					this.SendPropertyChanged("AgingBalance5Month");
					this.OnAgingBalance5MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousMonthBilled", DbType="Int")]
		public System.Nullable<int> PreviousMonthBilled
		{
			get
			{
				return this._PreviousMonthBilled;
			}
			set
			{
				if ((this._PreviousMonthBilled != value))
				{
					this.OnPreviousMonthBilledChanging(value);
					this.SendPropertyChanging();
					this._PreviousMonthBilled = value;
					this.SendPropertyChanged("PreviousMonthBilled");
					this.OnPreviousMonthBilledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoInAfter", DbType="Bit")]
		public System.Nullable<bool> GoInAfter
		{
			get
			{
				return this._GoInAfter;
			}
			set
			{
				if ((this._GoInAfter != value))
				{
					this.OnGoInAfterChanging(value);
					this.SendPropertyChanging();
					this._GoInAfter = value;
					this.SendPropertyChanged("GoInAfter");
					this.OnGoInAfterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoInAfterAmount", DbType="Float")]
		public System.Nullable<double> GoInAfterAmount
		{
			get
			{
				return this._GoInAfterAmount;
			}
			set
			{
				if ((this._GoInAfterAmount != value))
				{
					this.OnGoInAfterAmountChanging(value);
					this.SendPropertyChanging();
					this._GoInAfterAmount = value;
					this.SendPropertyChanged("GoInAfterAmount");
					this.OnGoInAfterAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendToCollections", DbType="Bit")]
		public System.Nullable<bool> SendToCollections
		{
			get
			{
				return this._SendToCollections;
			}
			set
			{
				if ((this._SendToCollections != value))
				{
					this.OnSendToCollectionsChanging(value);
					this.SendPropertyChanging();
					this._SendToCollections = value;
					this.SendPropertyChanged("SendToCollections");
					this.OnSendToCollectionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContinueBilling", DbType="Bit")]
		public System.Nullable<bool> ContinueBilling
		{
			get
			{
				return this._ContinueBilling;
			}
			set
			{
				if ((this._ContinueBilling != value))
				{
					this.OnContinueBillingChanging(value);
					this.SendPropertyChanging();
					this._ContinueBilling = value;
					this.SendPropertyChanged("ContinueBilling");
					this.OnContinueBillingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CollectionNotes
		{
			get
			{
				return this._CollectionNotes;
			}
			set
			{
				if ((this._CollectionNotes != value))
				{
					this.OnCollectionNotesChanging(value);
					this.SendPropertyChanging();
					this._CollectionNotes = value;
					this.SendPropertyChanged("CollectionNotes");
					this.OnCollectionNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YellowTab", DbType="Bit")]
		public System.Nullable<bool> YellowTab
		{
			get
			{
				return this._YellowTab;
			}
			set
			{
				if ((this._YellowTab != value))
				{
					this.OnYellowTabChanging(value);
					this.SendPropertyChanging();
					this._YellowTab = value;
					this.SendPropertyChanged("YellowTab");
					this.OnYellowTabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousSequenceNumber", DbType="Int")]
		public System.Nullable<int> PreviousSequenceNumber
		{
			get
			{
				return this._PreviousSequenceNumber;
			}
			set
			{
				if ((this._PreviousSequenceNumber != value))
				{
					this.OnPreviousSequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._PreviousSequenceNumber = value;
					this.SendPropertyChanged("PreviousSequenceNumber");
					this.OnPreviousSequenceNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
